///WHAT IS JQUERY? -- IT IS A SIMPLIFIED WAY OF WRITING JAVASCRIPT TO MAKE JAVASCRIPT CODE SMALLER WE USE JQUERY
//$("h1").css("color","red")///#THIS  IS HOW WE CAN CHANGE THE COLOR OF THE FIRST HEADING TO RED COLOR USING  JQUERY 

$("Button").css("color","blue")

